export const initials = ["b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "ng", "h", "gw", "kw", "w", "z", "c", "s", "j"];

export const finalsByGroup ={
      aa: ["aa", "aai", "aau", "aam", "aan", "aang", "aap", "aat", "aak"],
      a: ["a", "ai", "au", "am", "an", "ang", "ap", "at", "ak"],
      e: ["e", "ei", "en", "eu", "em", "eng", "ep", "et", "ek"],
      i: ["i", "iu", "im", "in", "ip", "it", "ing", "ik"],
      o: ["o", "ou", "oi", "on", "ong", "ot", "ok"],
      oe: ["oe", "oeng", "oet", "oek"],
      eo: ["eoi", "eon", "eot"],
      u: ["u", "ui", "un", "ut", "um", "ung", "up", "uk"],
      yu: ["yu", "yun", "yut"],
      鼻音: ["m", "ng"],
    }

export const tones = ["1", "2", "3", "4", "5", "6"];

export const initial_pronunciations = {
  b: "baa1",
  p: "paa3",
  d: "daa2",
  t: "taa1",
  g: "gaa1",
  k: "kaa1",
  gw: "gwaa1",
  kw: "kwaa1",
  z: "zaa1",
  c: "caa1",
  m: "maa1",
  n: "naa5",
  ng: "ngaa4",
  f: "faa1",
  s: "saa1",
  h: "haa1",
  w: "waa1",
  j: "jaa1",
  l: "laa1",
}

export const final_pronunciations = {
  m: "m4",
  ng: "ng4",
  i: "si1",
  iu: "siu1",
  im: "sim2",
  in: "sin1",
  ip: "sip3",
  it: "sit3",
  ing: "sing1",
  ik: "sik1",
  yu: "syu1",
  yun: "syun1",
  yut: "syut3",
  u: "fu1",
  ui: "fui1",
  un: "fun1",
  ut: "fut3",
  ung: "fung1",
  uk: "fuk1",
  ei: "sei3",
  e: "se1",
  eu: "deu6",
  em: "lem2",
  eng: "zeng6",
  ep: "gep6",
  et: "pet6",
  ek: "sek6",
  eoi: "seoi1",
  eon: "seon1",
  eot: "seot1",
  oeng: "goeng1",
  oet: "oet6",
  oek: "goek6",
  ou: "hou2",
  o: "ho2",
  oi: "hoi1",
  on: "hon3",
  ong: "hong1",
  ot: "hot3",
  ok: "hok6",
  a: "la3",
  ai: "zai1",
  au: "zau1",
  am: "zam1",
  an: "zan1",
  ang: "zang1",
  ap: "zap1",
  at: "zat6",
  ak: "zak1",
  aa: "zaa1",
  aai: "zaai1",
  aau: "zaau1",
  aam: "zaam6",
  aan: "zaan3",
  aang: "zaang6",
  aap: "zaap6",
  aat: "zaat3",
  aak: "zaak6",
}